name: "godot-ci export"
on:
  push:
    branches:
      - main
    tags:
      - v*
permissions:
  contents: write
  id-token: write
  attestations: write

env:
  GODOT_VERSION: 4.6.1
  PROJECT_PATH: .

jobs:
  export-win64:
    name: Windows x64 Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows x64 Build
        run: |
          mkdir -v -p build/win64
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/win64/Godot-Show_win64.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64
          path: build/win64

  export-linux_x86_x64:
    name: Linux x86/x64 Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux x86/x64 Build
        run: |
          mkdir -v -p build/linux_x86_x64
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux_x86_x64/Godot-Show_linux.x86_64"
          ls -lah "$EXPORT_DIR/linux_x86_x64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_x86_x64
          path: build/linux_x86_x64

  export-web:
    name: Web Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/Godot-Show_web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/Godot-Show_web/index.html"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/Godot-Show_web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/Godot-Show_web # The folder the action should deploy.

  export-mac:
    name: MacOS Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: MacOS Build
        run: |
          mkdir -v -p build/macos
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/macos/Godot-Show_macos.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/macos

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [export-win64, export-linux_x86_x64, export-mac]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v5
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          output-file: 'sbom.spdx.json'
      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v2
        with:
          subject-path: |
            linux_x86_x64/Godot-Show_linux.x86_64
            win64/Godot-Show_win64.exe
            macos/Godot-Show_macos.zip
          sbom-path: 'sbom.spdx.json'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          preserve_order: true
          files: |
            linux_x86_x64/Godot-Show_linux.x86_64
            win64/Godot-Show_win64.exe
            macos/Godot-Show_macos.zip
